#Bot language/Язык ботов (en_US ru_RU uk_UA de_DE)
language: "en_US"
#Server IP/Айпи адрес сервера
ip: "localhost"
#Server Port/Порт сервера
port: 25565
#Bot password/Пароль ботов
password: "123412341234"
#Delay between connections (in ms)/Задержка между подключениями (в мс)
interval: 8000
#Minecraft version/Версия майнкрафта
version: "1.18.2"
